"""Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms"""

a = 1
b = 2
#stated in question starting with 1 and 2 so we define initial value of a and b, the first 2 terms of the sequence
tt = 0
while b < 4000000:
    if b%2 == 0: #to make sure b is divisible by 2 == even number
        tt +=b #the number will be added together
    c = a+b #calculating the next term
    a = b #redefine a and b for the next calculation
    b = c
print(tt)
    
